name = "chieftain-rss"
main = "src/index.ts"
compatibility_date = "2023-10-16"

routes = [
	{ pattern = "chieftain-rss.based.zone", custom_domain = true }
]

[[kv_namespaces]]
binding = "CHIEFTAIN_KV"
id = "53f0abfccb484a6fbb4469cb858f832c"
preview_id = "aec9d1031d854a1ea6d5269044b28c30"

[[r2_buckets]]
binding = "CHIEFTAIN_BUCKET"
bucket_name = "chieftain-articles"
preview_bucket_name = "chieftain-articles-staging"

